#!/bin/sh

STAGED_FILES=$(git diff --cached --name-only)

echo "Running linting, type checking, and tests..."
npm run check
if [ $? -ne 0 ]; then
	echo "Checks failed."
	exit 1
fi

for file in $STAGED_FILES; do
	if [ -f "$file" ]; then
		git add "$file"
	fi
done

echo "Pre-commit checks passed."
